/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/
#include <stdlib.h>
#include <stdio.h>
#include "calc_primes.h"


unsigned int tri_num(int n) {
	return n*(n+1) / 2;
}

int main() {
	/* Find number of divisors by doing a prime factorization, then fining
	 * the number of combinations of prime factors. */
	// NB:  Brute force was much more efficient.
#define FACT_SZ 1000000
	size_t fact[FACT_SZ];
	unsigned int cur_tri_num,combos,i,j;
	for(i=1;1;++i) {
		cur_tri_num = tri_num(i);
		if(prime_factorize(cur_tri_num,fact,FACT_SZ)) {
			printf("Prime factor vector not large enough.\n");
		}
		combos = 0;
		for(j= 0; j<FACT_SZ; ++j) {
			if(fact[j]) combos+=fact[j]+1 /*for none*/;
		}
		if(combos>500) {
			printf("Triangle %d, %d\n",i,cur_tri_num);
			return 0;
		}
	}
}
