/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/

#include <stdio.h>

int main() {
	unsigned long lastNo = 1;
	unsigned long curNo = 1;
	unsigned long nextNo;
	unsigned long total = 0;
	while(curNo<4000000UL) {
		if(curNo%2==0) {
			total+=curNo;
		}
		if(total>(1UL<<63)) printf("Warning:  Overflow likely!\n");
		nextNo = lastNo+curNo;
		lastNo = curNo;
		curNo = nextNo;
	}
	printf("Total: %ld\n",total);

	return 0;	
}
